### ISSUE TITLE
Suggestion. Check that seed's array does not containt zero elements

### ISSUE THREAD

**Issue by DoumanAsh** [stainless-steel/random#1]
In case if it is zero it would be sad? :)
Maybe to have some default seed also?

**Comment by IvanUkhov** [comment]
@DoumanAsh, thanks for the suggestion! I’ve added an [assertion](https://github.com/stainless-steel/random/blob/054e9d425a517711c0cd6447ac3c0a8d535e9b2a/src/xorshift.rs#L21) to check that at least one bit of the seed is nonzero. Regarding default values, there is [one](https://github.com/stainless-steel/random/blob/054e9d425a517711c0cd6447ac3c0a8d535e9b2a/src/lib.rs#L98) actually; however, it is set only if one uses the `random::default()` wrapper instead of instantiating a particular algorithm directly (right now only `Xorshift128Plus`). The idea is to keep the algorithms pristine, without any preconceptions or biases.

Regards,
Ivan

**Comment by DoumanAsh** [comment]
It's good. I think assertion is enough to ensure that it will be used right so i'll close issue :)
